### ISSUE TITLE
Update to 1.21 please!

### ISSUE THREAD

**Issue by alexweber** [CartoonishVillain/VillainousHordeManager#1]
... and thanks for making this mod!

**Comment by CartoonishVillain** [comment]
Working on incapacitated 1.21 this week. Next week will (probably) be the horde manager.

**Comment by CartoonishVillain** [comment]
1.21 port complete ahead of schedule. Turns out it's a lot easier when I figure out what I'm doing.

**Comment by alexweber** [comment]
Thank you!

@CartoonishVillain I did run into an error trying to run a json horde using the example file, the other 2 commands work fine too....

**Comment by CartoonishVillain** [comment]
Can I get a log on the issue? The example file ran fine in live environment testing, so I'm curious to see what went wrong

**Comment by alexweber** [comment]
Getting unknown or incomplete command with not much else: 
![2024-08-05_11 45 46](https://github.com/user-attachments/assets/2596fceb-b581-4bbf-9272-4ef8c74b774e)

json file is the same one from the sample, uploaded in the minecraft root alongside mods folder

**Comment by alexweber** [comment]
> Can I get a log on the issue? The example file ran fine in live environment testing, so I'm curious to see what went wrong

Apologies, it's just a user error on my end.  Maybe I just misread the docs but either way when you try the command with no args it fails saying incomplete or not found command which i supppose isn't wrong but itsn't helpful either... thanks for the quick responses!

**Comment by CartoonishVillain** [comment]
I'll look into seeing if I can make it better. I'm admittedly still not great with brigadier syntax, but it could be cool if the swarm list could load in and such.

**Comment by alexweber** [comment]
It was late last night I felt pretty embarassed trying it again today and it was simple, and I'm a programmer too 🤦 

Either way I think it might be a common mistake but I'd recommend just a small update to the readme example to actually have a swam as an arg because lazy ppl like myself tend to copy and paste... and maybe a better error message when no args are available, I unfortunately work in another stack entirely :)  

Thanks for the amazing mod!
